function [RptgenML_CReport1] = buildreport
%BUILDREPORT
 
%  Auto-generated by MATLAB on 17-Jul-2024 14:38:37
 
% Create RptgenML.CReport
RptgenML_CReport1 = RptgenML.CReport;
% setedit(RptgenML_CReport1);
 
% Create rptgen.cfr_titlepage
rptgen_cfr_titlepage1 = rptgen.cfr_titlepage('Subtitle','subject',...
'Title','Recon All');
rptgen_cfr_text1 = rptgen.cfr_text;
set(rptgen_cfr_titlepage1,'AbstractComp',rptgen_cfr_text1);
rptgen_cfr_text2 = rptgen.cfr_text;
set(rptgen_cfr_titlepage1,'LegalNoticeComp',rptgen_cfr_text2);
rptgen_cfr_image1 = rptgen.cfr_image('FileName','','MaxViewportSize',[7 9]);
set(rptgen_cfr_titlepage1,'ImageComp',rptgen_cfr_image1);
setParent(rptgen_cfr_titlepage1,RptgenML_CReport1);
 
% Create rptgen.cfr_section
rptgen_cfr_section1 = rptgen.cfr_section('StyleName','rgChapterTitle',...
'SectionTitle','Autorecon 1');
setParent(rptgen_cfr_section1,RptgenML_CReport1);
 
% Create rptgen.cfr_ext_table
rptgen_cfr_ext_table1 = rptgen.cfr_ext_table('NumCols','5',...
'TableTitle','Recon');
setParent(rptgen_cfr_ext_table1,rptgen_cfr_section1);
 
% Create rptgen.cfr_ext_table_colspec
rptgen_cfr_ext_table_colspec1 = rptgen.cfr_ext_table_colspec('ColName',...
'Reconstruction Steps');
setParent(rptgen_cfr_ext_table_colspec1,rptgen_cfr_ext_table1);
 
% Create rptgen.cfr_ext_table_colspec
rptgen_cfr_ext_table_colspec2 = rptgen.cfr_ext_table_colspec('ColNum','2',...
'ColName','Individual Flag');
setParent(rptgen_cfr_ext_table_colspec2,rptgen_cfr_ext_table1);
 
% Create rptgen.cfr_ext_table_head
rptgen_cfr_ext_table_head1 = rptgen.cfr_ext_table_head;
setParent(rptgen_cfr_ext_table_head1,rptgen_cfr_ext_table1);
 
% Create rptgen.cfr_ext_table_row
rptgen_cfr_ext_table_row1 = rptgen.cfr_ext_table_row;
setParent(rptgen_cfr_ext_table_row1,rptgen_cfr_ext_table_head1);
 
% Create rptgen.cfr_ext_table_entry
rptgen_cfr_ext_table_entry1 = rptgen.cfr_ext_table_entry;
setParent(rptgen_cfr_ext_table_entry1,rptgen_cfr_ext_table_row1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph1 = rptgen.cfr_paragraph;
rptgen_cfr_text3 = rptgen.cfr_text('isBold',true,...
'Content','Reconstruction step');
set(rptgen_cfr_paragraph1,'ParaTextComp',rptgen_cfr_text3);
setParent(rptgen_cfr_paragraph1,rptgen_cfr_ext_table_entry1);
 
% Create rptgen.cfr_ext_table_entry
rptgen_cfr_ext_table_entry2 = rptgen.cfr_ext_table_entry;
setParent(rptgen_cfr_ext_table_entry2,rptgen_cfr_ext_table_row1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph2 = rptgen.cfr_paragraph;
rptgen_cfr_text4 = rptgen.cfr_text('isBold',true,...
'Content','Individual Flag');
set(rptgen_cfr_paragraph2,'ParaTextComp',rptgen_cfr_text4);
setParent(rptgen_cfr_paragraph2,rptgen_cfr_ext_table_entry2);
 
% Create rptgen.cfr_ext_table_foot
rptgen_cfr_ext_table_foot1 = rptgen.cfr_ext_table_foot;
setParent(rptgen_cfr_ext_table_foot1,rptgen_cfr_ext_table1);
 
% Create rptgen.cfr_ext_table_row
rptgen_cfr_ext_table_row2 = rptgen.cfr_ext_table_row;
setParent(rptgen_cfr_ext_table_row2,rptgen_cfr_ext_table_foot1);
 
% Create rptgen.cfr_ext_table_entry
rptgen_cfr_ext_table_entry3 = rptgen.cfr_ext_table_entry;
setParent(rptgen_cfr_ext_table_entry3,rptgen_cfr_ext_table_row2);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph3 = rptgen.cfr_paragraph;
rptgen_cfr_text5 = rptgen.cfr_text('Content','Foot 1');
set(rptgen_cfr_paragraph3,'ParaTextComp',rptgen_cfr_text5);
setParent(rptgen_cfr_paragraph3,rptgen_cfr_ext_table_entry3);
 
% Create rptgen.cfr_ext_table_entry
rptgen_cfr_ext_table_entry4 = rptgen.cfr_ext_table_entry;
setParent(rptgen_cfr_ext_table_entry4,rptgen_cfr_ext_table_row2);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph4 = rptgen.cfr_paragraph;
rptgen_cfr_text6 = rptgen.cfr_text('Content','Foot 2');
set(rptgen_cfr_paragraph4,'ParaTextComp',rptgen_cfr_text6);
setParent(rptgen_cfr_paragraph4,rptgen_cfr_ext_table_entry4);
 
% Create rptgen.cfr_ext_table_body
rptgen_cfr_ext_table_body1 = rptgen.cfr_ext_table_body;
setParent(rptgen_cfr_ext_table_body1,rptgen_cfr_ext_table1);
 
% Create rptgen.cfr_ext_table_row
rptgen_cfr_ext_table_row3 = rptgen.cfr_ext_table_row;
setParent(rptgen_cfr_ext_table_row3,rptgen_cfr_ext_table_body1);
 
% Create rptgen.cfr_ext_table_entry
rptgen_cfr_ext_table_entry5 = rptgen.cfr_ext_table_entry;
setParent(rptgen_cfr_ext_table_entry5,rptgen_cfr_ext_table_row3);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph5 = rptgen.cfr_paragraph;
rptgen_cfr_text7 = rptgen.cfr_text('Content',...
['',newline,'File I/O and conversion']);
set(rptgen_cfr_paragraph5,'ParaTextComp',rptgen_cfr_text7);
setParent(rptgen_cfr_paragraph5,rptgen_cfr_ext_table_entry5);
 
% Create rptgen.cfr_ext_table_entry
rptgen_cfr_ext_table_entry6 = rptgen.cfr_ext_table_entry;
setParent(rptgen_cfr_ext_table_entry6,rptgen_cfr_ext_table_row3);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph6 = rptgen.cfr_paragraph;
rptgen_cfr_text8 = rptgen.cfr_text('Content',['',newline,'-i <invol1>']);
set(rptgen_cfr_paragraph6,'ParaTextComp',rptgen_cfr_text8);
setParent(rptgen_cfr_paragraph6,rptgen_cfr_ext_table_entry6);
 
% Create rptgen.cfr_ext_table_row
rptgen_cfr_ext_table_row4 = rptgen.cfr_ext_table_row;
setParent(rptgen_cfr_ext_table_row4,rptgen_cfr_ext_table_body1);
 
% Create rptgen.cfr_ext_table_entry
rptgen_cfr_ext_table_entry7 = rptgen.cfr_ext_table_entry;
setParent(rptgen_cfr_ext_table_entry7,rptgen_cfr_ext_table_row4);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph7 = rptgen.cfr_paragraph;
rptgen_cfr_text9 = rptgen.cfr_text('Content',...
['',newline,'Additional T1 volumes of the subject']);
set(rptgen_cfr_paragraph7,'ParaTextComp',rptgen_cfr_text9);
setParent(rptgen_cfr_paragraph7,rptgen_cfr_ext_table_entry7);
 
% Create rptgen.cfr_ext_table_entry
rptgen_cfr_ext_table_entry8 = rptgen.cfr_ext_table_entry;
setParent(rptgen_cfr_ext_table_entry8,rptgen_cfr_ext_table_row4);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph8 = rptgen.cfr_paragraph;
rptgen_cfr_text10 = rptgen.cfr_text('Content',...
['',newline,'-i <invol2> optional']);
set(rptgen_cfr_paragraph8,'ParaTextComp',rptgen_cfr_text10);
setParent(rptgen_cfr_paragraph8,rptgen_cfr_ext_table_entry8);
 
