function datasetStructure = cc_readDatasetStructure(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DATASETSTRUCTURE = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DATASETSTRUCTURE = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  datasetStructure = importfile("C:\Users\diell\OneDrive - McGill University\6.Code\StormNet\data\PAD7\data_release_7.0_Info\cleaned_dataset_structure.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Jul-2024 12:28:25

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "/";

% Specify column names and types
opts.VariableNames = ["data_release", "dataset", "subject", "session", "modality", "file", "file_deriv"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["data_release", "dataset", "subject", "session", "modality", "file", "file_deriv"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["data_release", "dataset", "subject", "session", "modality", "file", "file_deriv"], "EmptyFieldRule", "auto");

% Import the data
datasetStructure = readtable(filename, opts);


%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "";

% Specify column names and types
opts.VariableNames = "paths";
opts.VariableTypes = "string";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "paths", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "paths", "EmptyFieldRule", "auto");

% Import the data
datasetPaths = readtable(filename, opts);

datasetStructure.data_release = datasetPaths.paths; 
end