function freeview_gtmseg(subjectsDir, sourceSubject)
% sourceSubject = 'sub-MTL0005'; 
cd (fullfile(subjectsDir, sourceSubject))
cmd = ['freeview' ...
    ' -volume ./mri/orig.mgz'...
    ' -volume ./mri/aseg.mgz:opacity=0.5'...
    ' -volume ./mri/nu.mgz'...
    ' -volume ./mri/aseg.mgz'...
    ' -volume ./mri/gtmseg.mgz:colormap=lut'...
    ' -surface ./surf/lh.white:edgecolor=yellow'...
    ' -surface ./surf/rh.white:edgecolor=yellow'...
    ' -surface ./surf/lh.pial:edgecolor=red:overlay=./surf/lh.thickness'...
    ' -surface ./surf/rh.pial:edgecolor=red:annot=./label/rh.aparc.annot'];

full_cmd = sprintf('export FREESURFER_HOME=%s; source $FREESURFER_HOME/SetUpFreeSurfer.sh; %s', ...
    getenv('FREESURFER_HOME'), cmd);
system(full_cmd);


end