function freeviewPETtemplate (subjectsDir, sourceSubject, petTemplate)
cd (fullfile(subjectsDir, sourceSubject))
path2template = fullfile ('./pet', petTemplate, 'template.nii.gz');

cmd = ['freeview' ...
    ' -hide-3d-slices'...
    ' -volume ./mri/orig.mgz' ...
    ' -volume ' path2template ...
    ' -surface ./surf/lh.white:edgecolor=yellow'...
    ' -surface ./surf/rh.white:edgecolor=yellow'...
    ' -surface ./surf/lh.pial:edgecolor=red:overlay=./surf/lh.thickness'...
    ' -surface ./surf/rh.pial:edgecolor=red:annot=./label/rh.aparc.annot'];

full_cmd = sprintf('export FREESURFER_HOME=%s; source $FREESURFER_HOME/SetUpFreeSurfer.sh; %s', ...
    getenv('FREESURFER_HOME'), cmd);
system(full_cmd);

end
