function freeviewPETFrames(subjectsDir, sourceSubject)
% sourceSubject = 'sub-MTL0005'; 
cd (fullfile(subjectsDir, sourceSubject))
cmd = ['freeview' ...
    ' -volume ./mri/T1.mgz'...
    ' -volume ./mri/aseg.mgz:opacity=0.5'...
    ' -volume ./pet/18FNAV4694_pet/template_mean_suvr.mgz' ...
    ' -volume ./pet/18FNAV4694_pet/mgx.ctxgm_coreg.mgz:colormap=heat:smoothed=1:heatscale=0,2.5,5' ...
    ' -volume ./pet/18FNAV4694_pet/template_mean.mgz' ...
    ' -surface ./surf/lh.white:edgecolor=yellow'...
    ' -surface ./surf/rh.white:edgecolor=yellow'...
    ' -surface ./surf/lh.pial:edgecolor=red:overlay=./pet/lh_surf_suvr.mgz'...
     ' -surface ./surf/lh.pial:edgecolor=red:overlay=./pet/rh_surf_suvr.mgz'...
    ' -surface ./surf/rh.pial:edgecolor=red:annot=./label/rh.aparc.annot'];

fs_execute(cmd)

end