function gtm = fs_gtm_stats(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GTM = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  GTM = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  gtm = importfile("/export02/export01/data/toolboxes/freesurfer/subjects/sub-MTL0005/pet/18FNAV4694_pet/template_mean_gtmpvc/gtm.stats.dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Jul-2024 19:56:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["\t", " "];

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "roi_idx", "roi_name", "tissue_class", "pet_voxels", "variance", "uptake", "residual"];
opts.SelectedVariableNames = ["roi_idx", "roi_name", "tissue_class", "pet_voxels", "variance", "uptake", "residual"];
opts.VariableTypes = ["string", "string", "double", "string", "categorical", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "roi_name"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "roi_name", "tissue_class"], "EmptyFieldRule", "auto");

% Import the data
gtm = readtable(filename, opts);

end