function outputPVC = fs_pet_PVC (subjectsDir, sourceSubject, templatePETDirectory, coregisteredVolume, registrationFile)

% templateFile = fullfile(selectedTemplateDir,'template_raw_mean.mgz');
% registrationFile = fullfile(selectedTemplateDir , 'template.reg.lta');
segmentationFile = fullfile (subjectsDir, sourceSubject, '/mri/gtmseg.mgz');

templatePET = fullfile(templatePETDirectory, coregisteredVolume);
[~, a , ~] =fileparts(coregisteredVolume);
[~, b , ~] =fileparts(a);

% registrationFile = fullfile(templatePETDirectory, strcat(b,'.reg.lta'));
outputPVC = fullfile (templatePETDirectory, strcat(b,'_gtmpvc'));

% % with PVC 
% mgx - voxel must have at least 25% grey matter, otherwise set to 0
        % change mgx = 0.01 if you want to set it to 1%
cmd = ['mri_gtmpvc'...
    ' --i ' templatePET ...
    ' --reg ' registrationFile ...
    ' --psf 6 ' ...
    ' --seg ' segmentationFile ...
    ' --default-seg-merge ' ...
    ' --auto-mask 1 .05 ' ...
    ' --mgx .25 ' ...
    ' --rescale 7 8 46 47' ...
    ' --o ' outputPVC ...
    ' --threads 15'];
 
% without PVC
% cmd = ['mri_gtmpvc'...
%     ' --i ' templatePET ...
%     ' --reg ' registrationFile ...
%     ' --seg ' segmentationFile ...
%     ' --default-seg-merge ' ...
%     ' --auto-mask 1 .01 ' ...
%     ' --no-tfe ' ...
%     ' --rescale 7 8 46 47' ...
%     ' --o ' outputPVC ...
%     ' --threads 15'];

log_file = fullfile(templatePETDirectory, 'fs_pet_pvc_log.txt');
fs_execute(cmd)

diary(log_file);

disp(['Processing completed for ', sourceSubject])

diary off
cd(subjectsDir);
end
