function [r_surf, l_surf] = fs_project_pet(subjectsDir, sourceSubject, selectedTemplateDir,  inputVolume, inputRegistrationFile, outputFolder)

pet_volume = inputVolume; 
registration_file = inputRegistrationFile; 

output_right = fullfile(outputFolder, 'rh_suvr_paint');
output_left = fullfile(outputFolder, 'lh_suvr_paint');

log_file = fullfile(outputFolder, 'fs_surface_projection.txt');
   % ' --projfrac 0.5' ...  ' --cortex'   % ' --projfrac 0.5' ...' --cortex'

cmdRight = ['mri_vol2surf'...
    ' --src ' pet_volume ...
    ' --srcreg ' registration_file ...
    ' --hemi rh' ...
    ' --o ' output_right ...
    ' --out_type paint' ...
    ' --noreshape' ...
    ' --projfrac-avg .2 .8 .1' ...
    ' --fwhm 4 ' ...
    ' --cortex'...
  ];

% option to paint onto pial surface
    % -surf path2pialsurface

cmdLeft = ['mri_vol2surf'...
    ' --src ' pet_volume ...
    ' --srcreg ' registration_file ...
    ' --hemi lh' ...
    ' --o ' output_left ...
    ' --out_type paint' ...
    ' --noreshape' ...
    ' --projfrac-avg .2 .8 .1' ...
    ' --fwhm 4 ' ...
    ' --cortex'...
    ];

diary(log_file);

fs_execute(cmdRight);
fs_execute(cmdLeft);

   paintFileRight = strcat(output_right, '.w');
   paintFileLeft = strcat(output_left, '.w');
   
   [r_surf, l_surf] = fs_surf2surf (subjectsDir, sourceSubject, selectedTemplateDir, outputFolder, paintFileRight, paintFileLeft);


disp(['Processing completed for ', sourceSubject])

diary off

end