function [outputFileRight, outputFileLeft] = fs_surf2surf (subjectsDir, sourceSubject, templateDir, outputFolder, paintFileRight, paintFileLeft)
% Usage
%mri_surf2surf --srcsubject <source subject name> --srcsurfval <sourcefile> --trgsubject <target suhject name> --trgsurfval <target file> --hemi <hemifield> [options]

% example
% mri_surf2surf --hemi lh --srcsubject bert --srcsurfval thickness
% --src_type curv --trgsubject ico --trgicoorder 7 --trgsurfval bert-thickness-lh.img --trg_type analyze4d

outputFileRight = fullfile(outputFolder, 'rh_surf_suvr.mgz');

cmdRight = ['mri_surf2surf'...
    ' --srcsubject ' sourceSubject ...
    ' --srcsurfval ' paintFileRight ...
    ' --trgsubject ' sourceSubject ...
    ' --trgsurfval ' outputFileRight ...
    ' --hemi rh ' ...
    ' --src_type paint '
    ];

outputFileLeft = fullfile(outputFolder, 'lh_surf_suvr.mgz');

cmdLeft = ['mri_surf2surf'...
    ' --srcsubject ' sourceSubject ...
    ' --srcsurfval ' paintFileLeft ...
    ' --trgsubject ' sourceSubject ...
    ' --trgsurfval ' outputFileLeft ...
    ' --hemi lh ' ...
    ' --src_type paint '
    ];


fs_execute(cmdRight)
fs_execute(cmdLeft)
end