function [smoothedVolfname, smoothedVol] = fs_smooth(subjectsDir, sourceSubject, templateDir, volumeToSmooth, smoothFactor)

fullVolumeToSmooth = fullfile (templateDir, volumeToSmooth); 
% use brain mask to smooth
brainmask = fullfile(subjectsDir, sourceSubject, 'mri/brainmask.mgz');
maskedVol = fullfile(templateDir, 'template_mean_masked.mgz');
smoothedVolfname = 'template_mean_smoothed.mgz';
smoothedVol = fullfile(templateDir, 'template_mean_smoothed.mgz'); 

%smoothFactorString = '4'; 

cmd = ['mri_mask ' ...
    fullVolumeToSmooth ...
    ' ' ...
    brainmask ...
    ' ' ...
    maskedVol];

fs_execute(cmd); 

cmd = ['mri_convert' ...
        ' --fwhm ' smoothFactor ...
        ' ' ...
        maskedVol...
         ' ' ...
        smoothedVol ...
        ];

fs_execute(cmd)

end