function avg = fs_segstat_regions (segStatInputVol, segStatSeg, segStatOutput, regions)

        cmd = ['mri_segstats'...
            ' --seg ' segStatSeg ...
            ' --i ' segStatInputVol ...
            ' --id ' regions ...
            ' --avgwf ' segStatOutput]

        fs_execute(cmd)

      avgFile = importdata(segStatOutput);
        avg = mean(avgFile);
end